name: Releases

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Cache Godot
        id: cache-godot
        uses: actions/cache@v3
        with:
          path: godot
          key: godot-3.5.1
      - name: Cache Godot templates
        id: cache-godot-templates
        uses: actions/cache@v3
        with:
          path: godot-templates
          key: godot-templates-3.5.1
      - name: Setup Godot
        if: steps.cache-godot.outputs.cache-hit != 'true'
        run: |
          mkdir -p /tmp/godot
          mkdir -p godot
          wget -q -O /tmp/godot/godot.zip https://downloads.tuxfamily.org/godotengine/3.5.1/mono/Godot_v3.5.1-stable_mono_linux_headless_64.zip
          unzip -q /tmp/godot/godot.zip -d godot
      - name: Download Godot templates
        if: steps.cache-godot-templates.outputs.cache-hit != 'true'
        run: |
          mkdir -p /tmp/godot-templates
          mkdir -p godot-templates
          wget -q -O /tmp/godot-templates/templates.zip https://downloads.tuxfamily.org/godotengine/3.5.1/mono/Godot_v3.5.1-stable_mono_export_templates.tpz
          unzip -q /tmp/godot-templates/templates.zip -d godot-templates
      - name: Install Godot templates
        run: |
          mkdir -p $HOME/.local/share/godot/templates/3.5.1.stable.mono
          cp -r godot-templates/templates/* $HOME/.local/share/godot/templates/3.5.1.stable.mono
      - name: Export godot
        run: godot/Godot_v3.5.1-stable_mono_linux_headless_64/Godot_v3.5.1-stable_mono_linux_headless.64 --verbose --no-window --export "HTML5" html.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            html.zip
      - uses: actions/upload-artifact@v3
        with:
          name: mono-logs
          path: /home/runner/.local/share/godot/mono/mono_logs/
